# Source for Ruby to find the gems
source "https://rubygems.org"

gem 'rake' # our task manager
gem 'pry' # we freeze our program and get access to it
gem 'pry-doc', '~> 0.8.0' # we learn more about our methods by inspecting with show-doc and show-method
gem 'sqlite3' # our database
gem 'require_all' # how our files know about each other
gem 'activerecord', :require => "active_record" # magical activerecord
gem 'sinatra-activerecord' # access to the rake tasks that we use to create, alter and destroy tables in our DB from the console
